# Site settings
title:          JLST
description:    "Blog for DevOps, Automation and Web Development"
# baseurl:        "JLST"
# url:            "https://chesterhow.github.io"

# Author
author:
  name:         JLST
  # url:          https://chester.how
  email:        johnlimueltalusan@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate
  - jemoji

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

#defaults
defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
      author: "Limuel"